
microservice:
  payment-service:
    endpoint:
      uri: http://localhost:8989/payment/doPayment 
  order-service:
    endpoint:
      uri: http://localhost:8989/order/placeOrder 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
